### ISSUE TITLE
Mischievous Sanguini, Devil's Scythe, platty

### ISSUE THREAD

**Issue by zenseii** [teamrocketslime/RS3DS-Releases#12] opened 2019-08-08 00:30 UTC
### Description

Nr.1 Misspelling "Devile"
Nr.2 Misspelling "Mischevious"
Nr.3 **_Unsure:_** Sangui-rider should maybe be Sanguini-rider?
Nr.4 Misspelling "Platty"

Nr.5 "Gimmie" -> Gimme
Nr.6 Agh -> "Argh"
Nr.7 Remove "for".
Nr.8 Agh -> "Argh"
Nr.9 Ice statuEs
Nr.10 Remove "~~"
Nr.11 "teh". Also dialog text overflow.
Nr.12 Missing space between "Valley" and "to".
Nr.13 Heady should say "[...] we shouldn't have lowered[...]".
Nr.14 "Plattiepie" should be two words. Also half of it is blue.
Nr.15 Remove space before " I am"

### Location of bug
Nr.1 Item description in pause menu
Nr.2 All descriptions for Sanguini ship parts in ship part shop
Nr.3 Ship part description for Sanguini mast
Nr.4 In the description for Platy body ship part in ship part shop
Nr.5-15 Check screenshots.

### Excerpt or Screenshot

- [x] Nr. 1 
![2019-08-07_01-29-12 650_top](https://user-images.githubusercontent.com/12501091/62666569-3525c480-b984-11e9-9c6f-dedaa36b5928.png)

- [x] Nr.2 & Nr.3
![2019-08-07_02-05-43 008_top](https://user-images.githubusercontent.com/12501091/62666591-538bc000-b984-11e9-91ea-9db2a0cb1745.png)

- [x] Nr.4
![2019-08-07_02-04-26 387_top](https://user-images.githubusercontent.com/12501091/62666603-5dadbe80-b984-11e9-9f55-f7ceaef06ff9.png)

- [x] **Nr.5**
![2019-08-27_06-27-03 512_bot](https://user-images.githubusercontent.com/12501091/64502368-1d649780-d2c6-11e9-8d1e-c07be4e29847.png)
![2019-08-27_06-27-03 512_top](https://user-images.githubusercontent.com/12501091/64502369-1dfd2e00-d2c6-11e9-8474-af07e448553b.png)

- [x] **Nr.6**
![2019-08-30_00-04-17 527_bot](https://user-images.githubusercontent.com/12501091/64502373-25bcd280-d2c6-11e9-96fc-c923864d5b05.png)

- [x] **Nr.7**
![2019-08-30_21-53-29 288_top](https://user-images.githubusercontent.com/12501091/64502375-29505980-d2c6-11e9-8e7a-16696fc7ea8d.png)
![2019-08-30_21-53-29 288_bot](https://user-images.githubusercontent.com/12501091/64502376-29e8f000-d2c6-11e9-8fdf-afea5f0ea335.png)

- [x] **Nr.8**
![2019-08-30_22-41-35 239_bot](https://user-images.githubusercontent.com/12501091/64502380-30776780-d2c6-11e9-9b57-ab6958290875.png)
![2019-08-30_22-41-35 239_top_right](https://user-images.githubusercontent.com/12501091/64502381-30776780-d2c6-11e9-900e-493a9c131ac6.png)

- [x] **Nr.9**
![2019-08-30_22-48-20 278_top](https://user-images.githubusercontent.com/12501091/64502386-35d4b200-d2c6-11e9-8f89-18abf746f610.png)
![2019-08-30_22-48-20 278_bot](https://user-images.githubusercontent.com/12501091/64502387-366d4880-d2c6-11e9-95e2-a0a78590115c.png)

- [x] **Nr.10**
![2019-09-04_13-04-36 349_top](https://user-images.githubusercontent.com/12501091/64502392-3bca9300-d2c6-11e9-9bb4-6833f75888a2.png)
![2019-09-04_13-04-36 349_bot](https://user-images.githubusercontent.com/12501091/64502393-3bca9300-d2c6-11e9-8f62-5d55d0ca7a22.png)

- [x] **Nr.11**
![2019-09-05_06-38-38 996_top](https://user-images.githubusercontent.com/12501091/64502490-a54aa180-d2c6-11e9-8515-6519bc4bd353.png)
![2019-09-05_06-38-38 996_bot](https://user-images.githubusercontent.com/12501091/64502491-a54aa180-d2c6-11e9-9222-f1060bcaf8b0.png)

- [x] **Nr.12**
![2019-09-06_18-29-49 809_top](https://user-images.githubusercontent.com/12501091/64502498-ad0a4600-d2c6-11e9-9b76-9b170afd17ac.png)
![2019-09-06_18-29-49 809_bot](https://user-images.githubusercontent.com/12501091/64502500-ad0a4600-d2c6-11e9-8f2d-d7751d51dab7.png)

- [x] **Nr.13**

![2019-09-06_18-52-44 312_bot](https://user-images.githubusercontent.com/12501091/64502503-b09dcd00-d2c6-11e9-8867-ab722476e153.png)
![2019-09-06_18-52-44 312_top](https://user-images.githubusercontent.com/12501091/64502504-b09dcd00-d2c6-11e9-98f2-479a469910de.png)

- [x] **Nr.14**
![2019-09-08_17-48-10 133_top](https://user-images.githubusercontent.com/12501091/64502508-b5fb1780-d2c6-11e9-859b-a248923e61eb.png)
![2019-09-08_17-48-10 133_bot](https://user-images.githubusercontent.com/12501091/64502509-b5fb1780-d2c6-11e9-96ba-513218cd48c1.png)

- [x] **Nr. 15**
![2019-09-04_14-02-42 220_bot](https://user-images.githubusercontent.com/12501091/64502523-cca16e80-d2c6-11e9-81bc-43bbd5d56407.png)
![2019-09-04_14-02-42 220_top](https://user-images.githubusercontent.com/12501091/64502524-cca16e80-d2c6-11e9-8cbc-82906b12bde6.png)

**Comment by 1ted59** [comment] 2019-08-08 05:16
For Nr.1, calling it Devile's Scythe causes a next line in the trade goods menu as well. 
![bug](https://user-images.githubusercontent.com/24933689/62676802-0e629080-b97a-11e9-818b-c3d0bcf3609d.png)

**Comment by CakeLancelot** [comment] 2019-08-08 19:09
'Devile's Scythe' Was found the other day and fixed internally, I'll take a look at the other ones as well. Thanks.

**Comment by lgnmcrules** [comment] 2019-08-13 02:14
Fixed

**Comment by zenseii** [comment] 2019-09-09 04:39
Added more issues.

**Comment by zenseii** [comment] 2019-09-14 01:46
Actually, after thinking about it, in Nr.13 when Heady talks about lowering the bridge, I have no idea what he's talking about. This is because 1. Rocket Slime lowered the bridge himself , and 2. Lowering it or raising the bridge wouldn't have changed anything since he made it in anyways.

**Comment by lgnmcrules** [comment] 2019-09-21 06:56
Fixed

**Closed as completed by lgnmcrules** 2019-09-21 06:56 UTC
Labels: typos
